### ISSUE TITLE
Timed out error when trying to connect

### ISSUE THREAD

**Issue by ghost** [Jamie-/openvpn-api#28]
Hi, trying to connect to a VPN with

`v = openvpn_api.VPN(<IPAdress>, 443)`

`v.type` gives me `<VPNType.IP: 'ip'>`. When I connect to that IP using OpenVPN and my credentials, I connect with no issue. Here I'm getting with `v.connect()`:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/environment/openvpn-api/openvpn_api/vpn.py", line 73, in connect
    raise errors.ConnectError(str(e)) from None
openvpn_api.util.errors.ConnectError: timed out`

How can I avoid this? Is this related to missing credentials or something else is happening?

**Comment by shagunkam** [comment]
hi, can you able to resolve this issue <openvpn_api.vpn.VPN object at 0x7f85e86d8430>
Traceback (most recent call last):
  File "1.py", line 12, in <module>
    v.connect()
  File "/home/itechnolabs/vpn/env/lib/python3.8/site-packages/openvpn_api/vpn.py", line 63, in connect
    raise errors.ConnectError(str(e)) from None
openvpn_api.util.errors.ConnectError: timed out
